[aliases]
mine = ["log", "-r", "ancestors(mine() & mutable(), 3)"]
fetch = ["fetch", "--all-remotes", "--tracked"]
fetch-pr = ["util", "exec", "--", "gh", "pr", "checkout", "--detach"]

[revset-aliases]
"mine()" = 'author("arian@arianvp.me") | author("arian.vanputten@gmail.com")'
