name: Build deployments
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        # TODO
        deployment:
          - arianvp-me
          - t490s
          - ryzen
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the pushed commit
      uses: actions/checkout@v2
      with:
        path: pushed

    - name: Check out master
      uses: actions/checkout@v2
      with:
        path: master
        ref: master

    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: arianvp
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Compare changeset
      run: |
        old=$(nix-instantiate ./master -A deployments.${{ matrix.deployment }}.toplevel)
        new=$(nix-instantiate ./pushed -A deployments.${{ matrix.deployment }}.toplevel)
        nix run -f ./master nix-diff -c nix-diff --color=always $old $new

    - name: Build
      run: nix-build ./pushed -A deployments.${{ matrix.deployment }}.toplevel

    - name: Dump software list and security audit
      run: |
        mkdir -p report
        nix-store --query --requisites --include-outputs ./result > report/software.txt
        nix run -f ./master vulnix -c vulnix -w https://raw.githubusercontent.com/ckauhaus/nixos-vulnerability-roundup/master/whitelists/nixos-20.09.toml ./result | tee report/vulnerabilities.txt


    - name: Upload software report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: report-${{ matrix.deployment }}
        path: report/
