name: "Build deployments on pull request"
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the pushed commit
      uses: actions/checkout@v2
      with:
        path: pushed

    - name: Check out master
      uses: actions/checkout@v2
      with:
        path: master
        ref: master

    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: arianvp
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Compare changeset
      run: |
        old=$(nix-instantiate ./master -A deployments.t490s.toplevel)
        new=$(nix-instantiate ./pushed -A deployments.t490s.toplevel)
        nix run -f ./master nix-diff -c nix-diff --color=always $old $new

    - name: Build
      run: nix-build ./pushed -A deployments.t490s.toplevel
