name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          nix build .#frameworkISO
      - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: iso
          path: ${{ env.UPLOAD_PATH }}
      - name: build
        run: |
          nix build .#digitalOceanImage
      - run: echo "UPLOAD_PATH=$(readlink -f result)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: iso
          path: ${{ env.UPLOAD_PATH }}
          

 
