name: Pull request
on:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        deployment:
          - arianvp-me
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the pushed commit
      uses: actions/checkout@v2
      with:
        path: pushed

    - name: Check out master
      uses: actions/checkout@v2
      with:
        path: master
        ref: master

    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v10
      with:
        name: arianvp
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: |
        nix build -L ./master#nixosConfigurations.${{ matrix.deployment }}.config.system.build.toplevel --profile /tmp/nix-profile
        nix build -L ./pushed#nixosConfigurations.${{ matrix.deployment }}.config.system.build.toplevel --profile /tmp/nix-profile

    - name: Diff
      id: diff
      run: |
        nix profile diff-closures --profile /tmp/nix-profile | tee /tmp/diff.txt
        OUTPUT_DIFF="$(cat /tmp/diff.txt)"
        OUTPUT_DIFF="${OUTPUT_DIFF//'%'/'%25'}"
        OUTPUT_DIFF="${OUTPUT_DIFF//$'\n'/'%0A'}"
        OUTPUT_DIFF="${OUTPUT_DIFF//$'\r'/'%0D'}"
        echo "$OUTPUT_DIFF"
        echo "::set-output name=diff::$OUTPUT_DIFF"

    - name: Scan for security issues
      id: security
      run: |
        nix run nixpkgs/nixos-20.09#vulnix -- -w https://raw.githubusercontent.com/ckauhaus/nixos-vulnerability-roundup/master/whitelists/nixos-20.09.toml /tmp/nix-profile | tee /tmp/security.txt
        OUTPUT_SECURITY="$(cat /tmp/security.txt)"
        OUTPUT_SECURITY="${OUTPUT_SECURITY//'%'/'%25'}"
        OUTPUT_SECURITY="${OUTPUT_SECURITY//$'\n'/'%0A'}"
        OUTPUT_SECURITY="${OUTPUT_SECURITY//$'\r'/'%0D'}"
        echo "$OUTPUT_SECURITY"
        echo "::set-output name=security::$OUTPUT_SECURITY"

    - name: Post report
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          # Summary of changes

          For your information, I have made the following summary of changes.
          Please use this in your assement whether this commit should be merged.

          ## Version report

          ```
          ${{ steps.diff.outputs.diff }}
          ```

          ## Vulnerability report
          ```
          ${{ steps.security.outputs.security }}
          ```
