name: Update dependencies
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: Update dependencies
      run: |
        before=$(nix-instantiate -A deployments.t490s.toplevel)

        GITHUB_PATH= nix run -f . niv -c niv update

        after=$(nix-instantiate -A deployments.t490s.toplevel)

        echo "before=$before"
        echo "after=$after"
        test $before = $after
    - name: Create Pull Request if there was a change
      if: ${{ failure() }}
      uses: peter-evans/create-pull-request@v3.5.1
      with:
        path: after
        token: ${{ secrets.PAT }} # needed so that this triggers further flows. not ideal:
        commit-message: "chore: update dependencies"
        title: "chore: update dependencies"
        reviewers: "arianvp"
        branch: "chore/update-dependencies"
