name: Update dependencies
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - name: Update dependencies
      run: |
        before=$(nix-instantiate -A deployments.t490s.toplevel)

        GITHUB_PATH= nix run -f . niv -c niv update

        after=$(nix-instantiate -A deployments.t490s.toplevel)

        if [ $before != $after ]; then
          nix_diff=$(nix run -f . nix-diff -c nix-diff $before $after)
          echo "nix_diff=$nix_diff" >> $GITHUB_ENV
        fi

    - name: Create Pull Request if there was a change
      if: ${{ env.nix_diff }}
      uses: peter-evans/create-pull-request@v3.6.0
      with:
        token: ${{ secrets.PAT }} # needed so that this triggers further flows. not ideal:
        commit-message: |
          chore: update dependencies

          Summary of changes:
          ${{ env.nix_diff }}

        title: "chore: update dependencies"
        reviewers: "arianvp"
        branch: "chore/update-dependencies"
