name: Update dependencies
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.4.0

    - uses: cachix/install-nix-action@v14.1
      with:
        install_url: https://releases.nixos.org/nix/nix-2.4/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Update flake
      run: |
        nix flake update
        echo hello

    - uses: peter-evans/create-pull-request@v3.11.0
      with:
        token: ${{ secrets.PAT }} # needed so that this triggers further flows. not ideal.
        title: "chore: nix flake update"
        commit-message: "chore: nix flake update"
        branch: "chore/update-dependencies"
