name: Update dependencies
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0

    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
        extra_nix_config: |
          experimental-features = nix-command flakes

    - run:  nix flake update

    - uses: peter-evans/create-pull-request@v3.8.2
      with:
        token: ${{ secrets.PAT }} # needed so that this triggers further flows. not ideal.
        title: "chore: nix flake update"
        commit-message: "chore: nix flake update"
        branch: "chore/update-dependencies"
