name: Update dependencies
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Update flake
      run: |
        nix flake update
        echo hello

    - uses: peter-evans/create-pull-request@v3.8.2
      with:
        token: ${{ secrets.PAT }} # needed so that this triggers further flows. not ideal.
        title: "chore: nix flake update"
        commit-message: "chore: nix flake update"
        branch: "chore/update-dependencies"
